- name: Check if already installed
  stat: path='{{ ansible_user_dir }}/.cargo/bin/rustup'
  register: rustup_check

- when: rustup_check.stat.exists == false
  vars:
    rustup_installer_path: /tmp/install-rustup.sh
  block:

    - name: Download installer
      get_url:
        url: https://sh.rustup.rs
        dest: '{{ rustup_installer_path }}'
        mode: 0755

    - name: Execute installer
      command:
        cmd: '{{ rustup_installer_path }} --no-modify-path -y'
        creates: '{{ ansible_user_dir }}/.rustup'

    - name: Remove installer
      file: path='{{ rustup_installer_path }}' state=absent
