- name: Install dependencies
  become: true
  apt:
    state: latest
    name:
      - libpam0g-dev
      - libxcb1-dev

- name: lydm repository
  vars:
    ly_dir: /tmp/ly
  block:

    - name: Clone repo
      git:
        clone: yes
        depth: 1
        repo: https://github.com/cylgom/ly
        dest: "{{ ly_dir }}"

    - name: Clone repo submodules
      make: chdir="{{ ly_dir }}" target=github

    - name: Compile
      make: chdir="{{ ly_dir }}"

    - name: Install
      become: true
      make: chdir="{{ ly_dir }}" target=install
      notify: remove lydm repo

- name: Disable old display manager
  become: true
  service: name=display-manager enabled=no
  failed_when: false

- name: Enable service
  become: true
  service: name=ly enabled=yes
