- name: Install packages
  become: yes
  apt:
    state: latest
    name:
      - apt-transport-https
      - autoconf
      - automake
      - boxes
      - build-essential
      - ca-certificates
      - cmake
      - git
      - golang-go
      - jq
      - lolcat
      - nmap
      - software-properties-common
      - tar
      - texlive
      - texlive-latex-extra
      - unzip
      - vim
      - zip

- name: Install system-specific packages
  become: yes
  apt:
    state: latest
    name: "{{ system_specific | default([]) }}"

- name: Remove unused dependencies
  become: yes
  apt:
    autoremove: yes
