- name: Upgrade
  become: true
  apt: upgrade=dist

- name: Add extra PPAs
  become: true
  apt_repository:
    repo: "ppa:{{ item }}"
  loop: "{{ extra_ppas | default([]) }}"

- name: Install packages
  become: true
  apt:
    state: latest
    name:
      - apt-transport-https
      - autoconf
      - automake
      - boxes
      - build-essential
      - ca-certificates
      - cmake
      - git
      - golang-go
      - jq
      - lolcat
      - nmap
      - software-properties-common
      - tar
      - texlive
      - texlive-latex-extra
      - traceroute
      - unzip
      - vim
      - zip
      - zsh

- name: Install extra packages
  become: true
  apt:
    state: latest
    name: "{{ extra_pkgs | default([]) }}"

- name: Remove unused dependencies
  become: true
  apt: autoremove=yes
