- become: true
  block:

    - name: Upgrade
      apt: upgrade=dist

    - name: Add extra PPAs
      apt_repository:
        repo: "ppa:{{ item }}"
      loop: "{{ extra_ppas | default([]) }}"

    - name: Install packages
      apt:
        state: latest
        name:
          - apt-transport-https
          - autoconf
          - automake
          - boxes
          - build-essential
          - ca-certificates
          - cmake
          - git
          - golang-go
          - jq
          - lolcat
          - nmap
          - software-properties-common
          - tar
          - texlive
          - texlive-latex-extra
          - traceroute
          - unzip
          - vim
          - zip
          - zsh

    - name: Install extra packages
      apt:
        state: latest
        name: "{{ extra_pkgs | default([]) }}"

    - name: Remove unused dependencies
      apt: autoremove=yes
