- name: Check if already installed
  stat: path='{{ ansible_user_dir }}/.cargo/bin/rustup'
  register: rustup_check

- name: Get user info
  user: name='{{ primary_user }}' state=present
  register: user_info

- when: rustup_check.stat.exists == false
  become: true
  become_user: '{{ user_info.name }}'
  vars:
    rustup_installer_path: /tmp/install-rustup.sh
  block:

    - name: Download installer
      get_url:
        url: https://sh.rustup.rs
        dest: '{{ rustup_installer_path }}'
        mode: 0755

    - name: Execute installer
      command:
        cmd: '{{ rustup_installer_path }} --no-modify-path -y'
        creates: '{{ user_info.home }}/.rustup'

    - name: Remove installer
      file: path='{{ rustup_installer_path }}' state=absent
