---
- hosts: self
  vars:
    new_hostname: cantou

  roles:
    - hostname

    - apt-packages
    - pip-packages
    - youtube-dl
    - nodejs

    - apache2
    - apache2-ssl

    - dotpull-host

    - docker
    - docker-compose

    - nextcloud-server

    - custom-motd
    - custom-motd-screenfetch

    - sudo-as-admin-successful
    - selected-editor
    - ssh-key
    - oh-my-zsh
    - dotfiles

    - reboot-when-done
