---
- hosts: self
  vars:
    domain_name: cantou
    all_domain_names:
      - cantou

  roles:
    - hostname

    - role: install-packages
      apt_packages:
        - apt-transport-https
        - autoconf
        - automake
        - boxes
        - build-essential
        - ca-certificates
        - cmake
        - git
        - golang-go
        - jq
        - lolcat
        - nmap
        - software-properties-common
        - tar
        - texlive
        - texlive-latex-extra
        - traceroute
        - unzip
        - vim
        - zip
        - zsh

    - pip-packages

    - youtube-dl
    - nodejs

    - apache2
    - apache2-ssl

    - dotpull-host

    - docker
    - docker-compose

    - nextcloud-server

    - custom-motd
    - custom-motd-screenfetch

    - sudo-as-admin-successful
    - selected-editor
    - ssh-key
    - oh-my-zsh
    - dotfiles

    - reboot-when-done
