---
- hosts: self
  vars:
    primary_user: nelson
    domain_name: nelsonearle.com
    all_domain_names:
      - nelsonearle.com
      - www.nelsonearle.com
      - cloud.nelsonearle.com
      - www.cloud.nelsonearle.com
      - finance.nelsonearle.com
      - www.finance.nelsonearle.com
    nginx_default_domain_names:
      - nelsonearle.com
      - www.nelsonearle.com
    firefly_domain_name: finance.nelsonearle.com
    firefly_owner_email: admin@nelsonearle.com
  vars_prompt:
    - name: primary_user_password
      prompt: Primary User Password
      private: true
      unsafe: true
    - name: firefly_mysql_password
      prompt: Firefly III - MySQL Password
      private: true
      unsafe: true

  roles:

    # ==================================================
    # System Setup
    # ==================================================

    # - hostname

    # - custom-motd
    # - custom-motd-screenfetch

    # - role: install-packages
    #   yum_packages:
    #     - ca-certificates
    #     - git
    #     - jq
    #     - nmap
    #     - tar
    #     - traceroute
    #     - unzip
    #     - vim
    #     - zip
    #     - zsh

    - nginx
    - nginx-dotpull-host

    - docker
    - docker-compose

    # - nextcloud-server

    - firefly-iii

    # ==================================================
    # User Setup
    # ==================================================

    - primary-user

    # - oh-my-zsh
    # - dotfiles

    # ==================================================
    # End
    # ==================================================

    # - reboot-when-done
