---
- hosts: all
  vars:
    primary_user: nelson
    domain_name: nelsonearle.com
    nextcloud_domain_name: 'cloud.{{ domain_name }}'
    firefly_domain_name: 'finance.{{ domain_name }}'
    firefly_owner_email: admin@nelsonearle.com
    all_domain_names:
      - '{{ domain_name }}'
      - '{{ nextcloud_domain_name }}'
      - '{{ firefly_domain_name }}'

  roles:

    - auto-updates-disabled

    # ==================================================
    # System Setup
    # ==================================================

    - hostname
    - hosts-file

    - custom-motd
    - custom-motd-neofetch

    - role: install-packages
      apt_packages:
        - git
        - jq
        - nmap
        - tar
        - traceroute
        - unzip
        - vim
        - zip
        - zsh
      pip_packages:
        - virtualenv

    - nginx-dotpull-host

    - nginx-nextcloud-server

    - nginx-firefly-iii

    # ==================================================
    # User Setup
    # ==================================================

    - primary-user

    - user-sudo-as-admin-successful

    - user-selected-editor

    - user-oh-my-zsh

    - user-dotfiles

    # ==================================================
    # End
    # ==================================================

    - auto-updates-enabled

    # - reboot-when-done
