---
- hosts: self
  vars:
    primary_user: nelson
    domain_name: nelsonearle.com
    nextcloud_domain_name: 'cloud.{{ domain_name }}'
    firefly_domain_name: 'finance.{{ domain_name }}'
    firefly_owner_email: admin@nelsonearle.com
    all_domain_names:
      - '{{ domain_name }}'
      - 'www.{{ domain_name }}'
      - '{{ nextcloud_domain_name }}'
      - 'www.{{ nextcloud_domain_name }}'
      - '{{ firefly_domain_name }}'
      - 'www.{{ firefly_domain_name }}'

  roles:

    # ==================================================
    # System Setup
    # ==================================================

    - hostname

    # - custom-motd
    # - custom-motd-screenfetch

    - role: install-packages
      apt_packages:
        - git
        - jq
        - nmap
        - tar
        - traceroute
        - unzip
        - vim
        - zip
        - zsh

    - nginx-dotpull-host

    - nginx-nextcloud-server

    - nginx-firefly-iii

    # ==================================================
    # User Setup
    # ==================================================

    - primary-user

    # - oh-my-zsh
    # - dotfiles

    # ==================================================
    # End
    # ==================================================

    # - reboot-when-done
