---
- hosts: all
  become: true

  roles:
    - role: install-packages
      apt_ppas:
        - snwh/ppa
      apt_packages:
        - apt-transport-https
        - autoconf
        - automake
        - boxes
        - build-essential
        - ca-certificates
        - cmake
        - git
        - golang-go
        - jq
        - lolcat
        - nmap
        - paper-icon-theme
        - scrot
        - software-properties-common
        - tar
        - texlive
        - texlive-latex-extra
        - traceroute
        - unzip
        - vim
        - vlc
        - zip
        - zsh
