#!/usr/bin/env bash

cd -- "$(dirname -- "${BASH_SOURCE[0]}")"

[ -x art ] || exit 0

_AWK_LIB='
    function strip_ansi(line) {
        return gensub(/\x1b\[([0-9;]*[mGKHF]|\?[0-9]*[lh]|u|s)/, "", "g", line)
    }
'
_awk() {
    awk -e "$_AWK_LIB" "$@"
}

width() {
    local w width=0 old_ifs="$IFS"
    IFS=''
    while read -r line; do
        w="$(wc -m <<< "$line")"
        (( w > width )) && width="$w"
    done < <(sed -E 's/\x1b\[([0-9;]*[mGKHF]|\?[0-9]*[lh]|u|s)//g')
    IFS="$old_ifs"
    # Changing the IFS results in a lot of extra whitespace from `wc`
    # Line length includes terminating newline so -1
    echo "$(( width - 1 ))"
}

center() {
    local width="${1:-70}" input input_width offset
    input="$(cat)"
    input_width="$(width <<< "$input")"
    offset=$(( (width - input_width) / 2 ))
    [[ $offset < 1 ]] && offset=1

    _awk -v offset="$offset" -e '
        length > 0 { printf "%*s%s\n", offset, " ", $0 }
    ' <<< "$input"
}

fetch_info() {
    neofetch --no_config \
        --backend off \
        --color_blocks off \
        --disable resolution de wm wm_theme theme icons
}

# Credits: https://stackoverflow.com/a/11393884/5673922
IFS=$'\n' GLOBIGNORE='*' \
    command eval 'ART_FILES=( $(find art -type f -perm -ugo=x) )'

I="$(( ${#ART_FILES[@]} * RANDOM / 32768 ))"
ART="$("${ART_FILES[$I]}")"
ART_WIDTH="$(width <<< "$ART")"

echo -e "$ART"
printf '\n'
fetch_info | center "$ART_WIDTH"
