#!/usr/bin/env bash

cd -- "$(dirname -- "${BASH_SOURCE[0]}")"

[ -x art ] || exit 0

_python() {
    python3 -I -c "
def strip_ansi(line):
    import re
    return re.sub(r'\x1b\[([0-9;]*[mGKHF]|\?[0-9]*[lh]|u|s)', '', line)
$1
"
}

width() {
    _python '
import sys
print(max(len(strip_ansi(l.rstrip("\n"))) for l in sys.stdin))
'
}

center() {
    local width="${1:-70}" input input_width
    input="$(cat)"
    input_width="$(width <<< "$input")"
    _python "
import sys
offset = max(1, ($width - $input_width) // 2)
for l in sys.stdin:
    l = l.rstrip('\n')
    if len(l) > 0:
        print(' ' * offset, l, sep='')
" <<< "$input"
}

fetch_info() {
    neofetch --no_config \
        --backend off \
        --color_blocks off \
        --disable resolution de wm wm_theme theme icons
}

# Credits: https://stackoverflow.com/a/11393884/5673922
IFS=$'\n' GLOBIGNORE='*' \
    command eval 'ART_FILES=( $(find art -type f) )'

I="$(( ${#ART_FILES[@]} * RANDOM / 32768 ))"
ART="$(< "${ART_FILES[$I]}")"
ART_WIDTH="$(width <<< "$ART")"

echo
echo "$ART"
echo
fetch_info | center "$ART_WIDTH"
