- name: Get user info
  user: name='{{ primary_user }}' state=present
  register: user_info

- name: Silence the daily login message
  become: true
  become_user: '{{ primary_user }}'
  file:
    path: '{{ user_info.home }}/.hushlogin'
    state: touch
    access_time: preserve
    modification_time: preserve
