- become: true
  block:

    - name: Create account
      user:
        name: '{{ primary_user }}'
        create_home: true
        generate_ssh_key: true
        ssh_key_type: ed25519

    - name: Add user to groups (Debian)
      when: ansible_os_family == 'Debian'
      user:
        name: '{{ primary_user }}'
        append: true
        groups: adm,admin,systemd-journal

    - name: Add user to groups (Amazon)
      when: ansible_distribution == 'Amazon'
      user:
        name: '{{ primary_user }}'
        append: true
        groups: adm,systemd-journal,wheel
