- become: true
  block:

    - name: Create account
      user:
        name: '{{ primary_user }}'
        create_home: true

    - name: Generate Default SSH key
      when: >-
        (generate_default_ssh_key is defined and generate_default_ssh_key) and
        (default_ssh_key_comment is defined and default_ssh_key_comment)
      user:
        name: '{{ primary_user }}'
        generate_ssh_key: true
        ssh_key_file: .ssh/id_ed25519
        ssh_key_type: ed25519
        ssh_key_comment: '{{ default_ssh_key_comment }}'

    - name: Generate Personal SSH key
      when: >-
        (generate_personal_ssh_key is defined and generate_personal_ssh_key) and
        (personal_ssh_key_comment is defined and personal_ssh_key_comment)
      user:
        name: '{{ primary_user }}'
        generate_ssh_key: true
        ssh_key_file: .ssh/id_ed25519_personal
        ssh_key_type: ed25519
        ssh_key_comment: '{{ personal_ssh_key_comment }}'

    - name: Generate Work SSH key
      when: >-
        (generate_work_ssh_key is defined and generate_work_ssh_key) and
        (work_ssh_key_comment is defined and work_ssh_key_comment)
      user:
        name: '{{ primary_user }}'
        generate_ssh_key: true
        ssh_key_file: .ssh/id_ed25519_work
        ssh_key_type: ed25519
        ssh_key_comment: '{{ work_ssh_key_comment }}'

    - name: Add user to groups (Debian)
      when: ansible_os_family == 'Debian'
      user:
        name: '{{ primary_user }}'
        append: true
        groups: adm,systemd-journal

    - name: Add user to groups (Amazon)
      when: ansible_distribution == 'Amazon'
      user:
        name: '{{ primary_user }}'
        append: true
        groups: adm,systemd-journal,wheel
