- vars:
    dotfiles_repo_url: https://github.com/nelson137/.dot
  block:

    - name: Clone repo
      git:
        clone: yes
        depth: 1
        repo: '{{ dotfiles_repo_url }}'
        dest: '{{ ansible_user_dir }}/.dot'

    - name: Install dotfiles
      command: '{{ ansible_user_dir }}/.dot/deploy.sh'
