- name: Clone repo
  git:
    clone: yes
    repo: https://github.com/nelson137/.dot
    dest: ~/.dot

- name: Install dotfiles
  command: ~/.dot/deploy.sh

- name: Install Vundle
  git:
    clone: yes
    repo: https://github.com/VundleVim/Vundle.vim
    dest: ~/.vim/bundle/Vundle.vim
    depth: 1

- name: Install vim plugins
  command: vim +PluginInstall +qall
