- become: true
  block:

    - name: Disable default system info
      file:
        path: /etc/update-motd.d/50-landscape-sysinfo
        mode: -x
      failed_when: false

    - name: Install art files
      copy: src=art dest=/etc/update-motd.d/ mode=0755

    - name: Install custom header script
      copy: src=00-custom-header dest=/etc/update-motd.d/00-custom-header mode=0755
