- name: Create challenge container directory
  become: yes
  file: path=/docker/letsencrypt state=directory

- name: Copy docker-compose definition for challenge container
  become: yes
  copy: src=docker-compose.yml dest=/docker/letsencrypt/docker-compose.yml

- name: Copy nginx config for challenge
  become: yes
  template: src=nginx.conf.j2 dest=/docker/letsencrypt/nginx.conf

- name: Copy LetsEncrypt command script
  become: yes
  template: src=le-cmd.j2 dest=/docker/letsencrypt/le-cmd mode=0775

- name: Install dependencies for ansible docker modules
  become: yes
  pip:
    name:
      - docker
      - docker-compose

- name: Stop apache2 service
  become: yes
  service: name=apache2 state=stopped

- name: Start LetsEncrypt challenge container
  become: yes
  docker_compose: project_src=/docker/letsencrypt

- name: Get LetsEncrypt certificate
  become: yes
  block:

    - name: Get test LetsEncrypt certificate
      command:
        cmd: /docker/letsencrypt/le-cmd cert-get --staging
        creates: "/etc/letsencrypt/live/{{ domain }}"

    - name: Revoke and delete test LetsEncrypt certificate
      command:
        cmd: /docker/letsencrypt/le-cmd cert-revoke --staging
        removes: "/etc/letsencrypt/live/{{ domain }}"

    - name: Get LetsEncrypt certificate
      command:
        cmd: /docker/letsencrypt/le-cmd cert-get
        creates: "/etc/letsencrypt/live/{{ domain }}"

- name: Stop and remove LetsEncrypt challenge container
  become: yes
  docker_compose: project_src=/docker/letsencrypt state=absent

- name: Start apache2 service
  become: yes
  service: name=apache2 state=started

- name: Install cron job to renew the certificate
  become: yes
  cron:
    name: renew LetsEncrypt certificate
    user: root
    minute: '0'
    hour: '23'
    job: /docker/letsencrypt/le-cmd cert-renew

- name: Generate Diffie-Hellman parameters
  become: yes
  openssl_dhparam:
    size: 4096
    path: /etc/ssl/certs/dhparam.pem

- name: Enable apache modules
  become: yes
  apache2_module:
    name: "{{ item }}"
  loop:
    - rewrite
    - ssl

- name: Disable default SSL config
  become: yes
  command:
    cmd: a2ensite default-ssl
    removes: /etc/apache2/sites-enabled/default-ssl.conf

- name: Remove default SSL config
  become: yes
  file: path=/etc/apache2/sites-available/default-ssl.conf state=absent

- name: Copy SSL options config
  become: yes
  template:
    src: ssl-options.conf.j2
    dest: /etc/apache2/ssl-options.conf

- name: Copy default site config
  become: yes
  template: src=000-default.conf.j2 dest=/etc/apache2/sites-available/000-default.conf

- name: Restart apache2
  become: yes
  service: name=apache2 state=reloaded
