- name: Check if already installed
  stat: path='{{ ansible_user_dir }}/.oh-my-zsh' get_checksum=false get_mime=false
  register: omz_dir

- when: not omz_dir.stat.exists
  block:

    - name: Create a temporary file for the Install Script
      tempfile:
        suffix: .rustup-install-script
      register: omz_install_script_tempfile

    - name: Download the Install Script to the temporary file
      get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: '{{ omz_install_script_tempfile.path }}'
        mode: '0755'

    - name: Run the Install Script
      command:
        # `--unattended` is also sets `--skip-chsh` (don't change user shell)
        # and `RUNZSH=no` (don't run zsh after installation). Additionally, we
        # don't want to change the user shell here since it always prompts for
        # user confirmation.
        cmd: '{{ omz_install_script_tempfile.path }} --unattended --keep-zshrc'
        creates: '{{ ansible_user_dir }}/.oh-my-zsh'

  always:

    - name: Remove the Install Script temporary file
      file: path='{{ omz_install_script_tempfile.path }}' state=absent

- name: Change user shell to zsh
  become: true
  user: name='{{ ansible_user_id }}' shell=/usr/bin/zsh
