- become: true
  block:

    - name: Disable news
      lineinfile:
        path: /etc/default/motd-news
        regexp: "^(ENABLED)=1"
        line: '\1=0'

    - name: Disable scripts
      file:
        path: "/etc/update-motd.d/{{ item }}"
        mode: -x
      failed_when: false
      loop:
        - 10-help-text
        - 50-motd-news
        - 51-cloudguest
        - 88-esm-announce
        - 91-contract-ua-esm-status
        - 91-release-upgrade

    - when: ansible_distribution == 'Ubuntu'
      block:

        - name: Permanently disable Ubuntu Advantage systemd service (Ubuntu)
          systemd: name='{{ item }}' state=stopped masked=true
          loop:
            - ua-timer.service
            - ua-timer.timer
