- name: Disable news
  become: yes
  lineinfile:
    path: /etc/default/motd-news
    regexp: "^(ENABLED)=1"
    line: '\1=0'

- name: Disable scripts
  become: yes
  file:
    path: "/etc/update-motd.d/{{ item }}"
    mode: -x
  loop:
    - 10-help-text
    - 50-motd-news
    - 51-cloudguest
