- name: Add apt key
  become: yes
  apt_key:
    url: https://dl.teamviewer.com/download/linux/signature/TeamViewer2017.asc

- name: Download and install
  become: yes
  apt:
    deb: https://download.teamviewer.com/download/linux/teamviewer_amd64.deb
