- become: true
  block:

    - name: Create Docker plugins directory
      file: path=/usr/local/lib/docker/cli-plugins state=directory

    - name: Install Docker Compose
      get_url:
        url: 'https://github.com/docker/compose/releases/latest/download/docker-compose-linux-{{ ansible_architecture }}'
        dest: /usr/local/lib/docker/cli-plugins/docker-compose
        mode: '0755'
