- name: Install zsh
  apt: name=zsh state=latest

- name: Check if already installed
  stat:
    path: "{{ ansible_user_dir }}/.oh-my-zsh"
  register: oh_my_zsh

- name: Oh My Zsh
  when: oh_my_zsh.stat.exists == false
  block:

    - name: Download install script
      get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: /tmp/install-ohmyzsh
        mode: 0755

    - name: Execute install script
      command:
        cmd: /tmp/install-ohmyzsh --unattended
        creates: "{{ ansible_user_dir }}/.oh-my-zsh"
      notify:
        - remove install script

- name: Change user shell to zsh
  become: true
  user:
    name: "{{ ansible_user }}"
    shell: /usr/bin/zsh
