- name: Install zsh
  become: true
  apt: name=zsh state=latest

- name: Get user info
  user: name='{{ primary_user }}' state=present
  register: user_info

- name: Check if already installed
  stat: path='{{ user_info.home }}/.oh-my-zsh'
  register: oh_my_zsh

- name: Oh My Zsh
  when: oh_my_zsh.stat.exists == false
  become: true
  become_user: '{{ user_info.name }}'
  block:

    - name: Download install script
      get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: /tmp/install-ohmyzsh
        mode: 0755

    - name: Execute install script
      command:
        cmd: /tmp/install-ohmyzsh --unattended
        creates: '{{ user_info.home }}/.oh-my-zsh'
      notify: remove install script

- name: Change user shell to zsh
  become: true
  user: name='{{ user_info.name }}' shell=/usr/bin/zsh
