- name: Install neofetch
  become: true
  apt: name=neofetch state=latest

- name: Install custom header script
  become: true
  copy: src=00-custom-header dest=/etc/update-motd.d/00-custom-header mode=0755
