- name: Clone repo
  git:
    clone: true
    repo: 'https://github.com/nelson137/.dot'
    dest: '{{ ansible_user_dir }}/.dot'

- name: Install dotfiles
  command: '{{ ansible_user_dir }}/.dot/deploy.sh'
