- name: Add apt key
  become: true
  apt_key: url=https://dl.winehq.org/wine-builds/winehq.key

- name: Add apt repository
  become: true
  apt_repository:
    filename: wine
    repo: deb https://dl.winehq.org/wine-builds/ubuntu/ {{ ansible_lsb['codename'] }} main

- name: Install
  become: true
  apt: name='wine-stable-{{ bits }}' state=latest
  vars:
    bits: '{{ "amd64" if ansible_userspace_bits == "64" else "i386" }}'
