version: '3.1'

services:
  letsencrypt-docker:
    container_name: letsencrypt
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - /docker/letsencrypt/nginx.conf:/etc/nginx/conf.d/default.conf
      - /data/letsencrypt:/usr/share/nginx/html
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge
