#!/bin/bash

[ $EUID -ne 0 ] && {
    echo "Must be run as root"
    exit 1
}

a2dissite nextcloud
systemctl reload apache2
rm -f /etc/apache2/sites-available/nextcloud.conf
systemctl reload apache2

rm -rf /var/www/nextcloud

mysql -e "
    REVOKE ALL PRIVILEGES,GRANT OPTION FROM 'nextcloud'@'localhost';
    DROP USER IF EXISTS 'nextcloud'@'localhost';
    DROP DATABASE IF EXISTS nextcloud"
