- name: Check if already installed
  stat: path=/usr/bin/balena-etcher-electron
  register: etcher

- when: etcher.stat.exists == false
  vars:
    etcher_url: https://github.com/balena-io/etcher/releases/latest
  block:

    - name: Get latest version
      register: etcher_version
      shell:
        cmd: curl -sw '%{redirect_url}' "{{ etcher_url }}" -o /dev/null | grep -o '[0-9.]\+$'
        warn: no
      changed_when: false

    - name: Download and install
      become: true
      apt:
        deb: "{{ etcher_url }}/download/balena-etcher-electron_{{ etcher_version.stdout }}_amd64.deb"
