- name: Install dependencies
  become: true
  apt: name=apt-transport-https state=latest

- name: Add apt source
  become: true
  copy:
    src: sublime.list
    dest: /etc/apt/sources.list.d/sublime.list

- name: Add apt key
  become: true
  apt_key: url=https://download.sublimetext.com/sublimehq-pub.gpg

- name: Install
  become: true
  apt: name=sublime-text state=latest
