- name: Install dependencies
  become: yes
  apt: name=apt-transport-https state=latest

- name: Add apt source
  become: yes
  copy:
    src: sublime.list
    dest: /etc/apt/sources.list.d/sublime.list

- name: Add apt key
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    update_cache: yes

- name: Install
  become: yes
  apt: name=sublime-text state=latest
