- name: reload nginx
  become: true
  service: name=nginx state=reloaded

- name: update nextcloud htaccess
  become: true
  become_user: www-data
  command: php /var/www/nextcloud/occ maintenance:update:htaccess

- name: reindex nextcloud files
  become: true
  become_user: www-data
  command: php /var/www/nextcloud/occ files:scan "{{ nextcloud_admin_user }}"
