- become: true
  block:

    - name: Add apt key
      apt_key: url=https://download.docker.com/linux/ubuntu/gpg

    - name: Add apt repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb['codename'] }} stable"

    - name: Install
      apt: name=docker-ce state=latest

    - name: Add user to docker group
      user: name="{{ ansible_user }}" groups=docker
