- become: true
  block:

    - when: ansible_os_family == "Debian"
      vars:
        docker_keyring: /etc/apt/keyrings/docker.gpg
        docker_repo_url: https://download.docker.com/linux/ubuntu
        docker_keyring_url: '{{ docker_repo_url }}/gpg'
      block:

        - name: Add apt key (Debian)
          apt_key:
            url: '{{ docker_keyring_url }}'
            keyring: '{{ docker_keyring }}'

        - vars:
            _arch_map:
              aarch64: arm64
              armv6l: armhf
              armv7l: armhf
              i386: i386
              x86_64: amd64
            deb_arch: '{{ _arch_map[ansible_architecture] }}'
          block:

            - name: Add apt repository (Debian)
              apt_repository:
                repo: "deb [arch={{ deb_arch }} signed-by={{ docker_keyring }}] {{ docker_repo_url }} {{ ansible_lsb['codename'] }} stable"

        - name: Install (Debian)
          apt: name=docker-ce state=latest

    - name: Install Docker (Amazon)
      when: ansible_distribution == "Amazon"
      command:
        cmd: amazon-linux-extras install -y docker
        creates: /usr/bin/docker

    - name: Start & Enable Docker
      systemd: name=docker state=started enabled=true

    - name: Add user to docker group
      user: name="{{ primary_user }}" append=true groups=docker
