- name: Add apt key
  become: true
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: Add apt repository
  become: true
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb['codename'] }} stable"

- name: Install
  become: true
  apt: name=docker-ce state=latest

- name: Add user to docker group
  become: true
  user: name="{{ ansible_user }}" groups=docker
