- name: Install PHP dependencies
  become: yes
  apt:
    state: latest
    name:
      - libapache2-mod-php
      - libxml2
      - mariadb-server
      - php7.2
      - php7.2-bz2
      - php7.2-curl
      - php7.2-gd
      - php7.2-gmp
      - php7.2-intl
      - php7.2-mbstring
      - php7.2-mysql
      - php7.2-xml
      - php7.2-zip
      - php-imagick

- name: Check if already installed
  stat:
    path: /var/www/nextcloud
  register: nextcloud_dir

- name: Downloads
  vars:
    archive_url: https://download.nextcloud.com/server/releases/latest.tar.bz2
  when: nextcloud_dir.stat.exists == false
  block:

    - name: Download archive
      get_url:
        url: "{{ archive_url }}"
        dest: /tmp/nextcloud.tar.bz2
        checksum: "sha256:{{ archive_url }}.sha256"

    - name: Download Nextcloud's PGP key
      get_url:
        url: https://nextcloud.com/nextcloud.asc
        dest: /tmp/nextcloud.asc

    - name: Download archive PGP signature
      get_url:
        url: "{{ archive_url }}.asc"
        dest: /tmp/nextcloud.tar.bz2.asc

    - name: Import Nextcloud's PGP key
      command: gpg --import /tmp/nextcloud.asc
      notify:
        - remove nextcloud pgp key

    - name: Verify archive's PGP signature
      command: gpg --verify /tmp/nextcloud.tar.bz2.asc /tmp/nextcloud.tar.bz2
      notify:
        - remove nextcloud server archive pgp signature

    - name: Extract archive
      become: yes
      unarchive:
        remote_src: yes
        src: /tmp/nextcloud.tar.bz2
        dest: /var/www/nextcloud
        creates: /var/www/nextcloud
        owner: www-data
        group: www-data
      notify:
        - remove nextcloud server archive

- name: Enable apache modules
  become: yes
  apache2_module:
    name: "{{ item }}"
  loop:
    - dir
    - env
    - headers
    - mime
    - rewrite
    - ssl
  notify:
    - restart apache2

- name: Copy site config
  become: yes
  template: src=nextcloud.conf.j2 dest=/etc/apache2/sites-available/nextcloud.conf

- name: Enable site config
  become: yes
  command:
    cmd: a2ensite nextcloud
    creates: /etc/apache2/sites-enabled/nextcloud.conf
  notify:
    - restart apache2

- name: Copy MariaDB config
  become: yes
  copy:
    src: 60-nextcloud.cnf
    dest: /etc/mysql/mariadb.conf.d/60-nextcloud.cnf

- name: Check if MySQL database already setup
  become: yes
  shell: mysql -sNe 'USE nextcloud; SELECT @@character_set_database,@@collation_database' | grep -Pq 'utf8mb4\tutf8mb4_general_ci'
  register: nc_db_is_setup
  failed_when: false
  changed_when: false

- name: Delete any existing database
  when: nc_db_is_setup.rc != 0
  become: yes
  command: mysql -e 'DROP DATABASE IF EXISTS nextcloud'

- name: Setup MySQL database
  when: nc_db_is_setup.rc != 0
  become: yes
  command: mysql -e "CREATE DATABASE nextcloud CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci; CREATE USER IF NOT EXISTS '{{ db_user }}'@'localhost' IDENTIFIED BY '{{ db_pass }}'; GRANT ALL PRIVILEGES ON nextcloud.* TO '{{ db_user }}'@'localhost' IDENTIFIED BY '{{ db_pass }}'; FLUSH PRIVILEGES"

- name: Check if already installed
  stat: path=/var/www/nextcloud/config/config.php
  register: nc_config

- name: Install
  when: nc_config.stat.exists == false
  become: yes
  become_user: www-data
  command: php /var/www/nextcloud/occ maintenance:install --database mysql --database-name nextcloud --database-user "{{ db_user }}" --database-pass "{{ db_pass }}" --admin-user "{{ admin_user }}" --admin-pass "{{ admin_pass }}"

- name: Add trusted domain to config
  become: yes
  lineinfile:
    path: /var/www/nextcloud/config/config.php
    insertafter: "0 => 'localhost',"
    line: "    1 => 'cloud.{{ domain }}',"

- name: Fix url rewrite in config
  become: yes
  lineinfile:
    path: /var/www/nextcloud/config/config.php
    regexp: "  'overwrite\\.cli\\.url' => 'http://localhost',"
    line: "  'overwrite.cli.url' => 'https://cloud.{{ domain }}',"
  notify:
    - update nextcloud htaccess

- name: Add htaccess RewriteBase to config
  become: yes
  lineinfile:
    path: /var/www/nextcloud/config/config.php
    insertafter: 'overwrite.cli.url'
    line: "  'htaccess.RewriteBase' => '/',"
  notify:
    - update nextcloud htaccess

- name: Enable MySQL utf8mb4 charset in config
  become: yes
  lineinfile:
    path: /var/www/nextcloud/config/config.php
    insertafter: 'dbpassword'
    line: "  'mysql.utf8mb4' => true,"

- name: Cleanup Nextcloud files
  become: yes
  file:
    path: "/var/www/nextcloud/data/{{ admin_user }}/files/{{ item }}"
    state: absent
  loop:
    - Nextcloud intro.mp4
    - Nextcloud.png
    - Documents/Example.md
    - Documents/Example.odt
    - Documents/Nextcloud flyer.pdf
    - Documents/Readme.md
    - Photos
  notify:
    - reindex nextcloud files
