#!/bin/sh

set -e

[ "$EUID" -eq 0 ] && {
    echo 'error: must not be run as root' >&2
    exit 1
}

# Cache sudo password
sudo /bin/true

# Get target host
read -p 'Target Hostname: ' host
[ -n "$host" ] || exit 1

# Make sure the ansible apt repository is added
apt-cache policy | grep -q ansible || sudo add-apt-repository -yu ppa:ansible/ansible

# Install dependencies
sudo apt install -y ansible python3-pip

# Make sure ansible dependencies are installed
pip3 list --format columns | grep -q github3 || sudo -H pip3 install github3.py

# Pull down and execute play for configuring local system
ansible-pull --purge -U https://github.com/nelson137/dotpull --ask-vault-pass "$host.yml"
