- name: Install dependencies
  become: yes
  apt:
    state: latest
    name:
      - asciidoc
      - autoconf
      - automake
      - libev-dev
      - libpango1.0-dev
      - libstartup-notification0-dev
      - libyajl-dev
      - libxcb-cursor-dev
      - libxcb-icccm4-dev
      - libxcb-keysyms1-dev
      - libxcb-randr0-dev
      - libxcb-shape0-dev
      - libxcb-util0-dev
      - libxcb-xinerama0-dev
      - libxcb-xkb-dev
      - libxcb-xrm0
      - libxcb-xrm-dev
      - libxcb1-dev
      - libxkbcommon-dev
      - libxkbcommon-x11-dev
      - xmlto

- name: Get latest version
  shell:
    cmd: curl -sL https://api.github.com/repos/Airblader/i3/releases/latest | jq -r '.tag_name'
    warn: no
  register: i3_gaps_v
  changed_when: false

- name: Check if already downloaded
  stat:
    path: /tmp/i3-gaps
  register: i3_gaps

- when: i3_gaps.stat.exists == false
  block:

    - name: Download archive
      get_url:
        url: "https://github.com/Airblader/i3/releases/download/{{ i3_gaps_v.stdout }}/i3-{{ i3_gaps_v.stdout }}.tar.bz2"
        dest: /tmp/i3-gaps.tar.bz2

    - name: Create repo directory
      file: path=/tmp/i3-gaps state=directory

    - name: Extract archive
      command:
        cmd: tar xjf /tmp/i3-gaps.tar.bz2 -C /tmp/i3-gaps --strip-components 1
        warn: no
        creates: /tmp/i3-gaps/LICENSE
      notify:
        - remove i3-gaps archive

- name: Generate build scripts
  command:
    cmd: autoreconf --force --install
    chdir: /tmp/i3-gaps
    creates: /tmp/i3-gaps/configure

- name: Create build directory
  file: path=/tmp/i3-gaps/build state=directory

- name: Generate Makefiles
  command:
    chdir: /tmp/i3-gaps/build
    cmd: ../configure --prefix=/usr --sysconfdir=/etc --mandir=/usr/local/share/man --disable-sanitizers
    creates: /tmp/i3-gaps/build/Makefile

- name: Compile
  make: chdir=/tmp/i3-gaps/build

- name: Install
  become: yes
  make: chdir=/tmp/i3-gaps/build target=install
  notify:
    - remove i3-gaps repo
