- name: Install dependencies
  become: yes
  apt:
    state: latest
    name:
      - asciidoc
      - autoconf
      - automake
      - libev-dev
      - libpango1.0-dev
      - libstartup-notification0-dev
      - libyajl-dev
      - libxcb-cursor-dev
      - libxcb-icccm4-dev
      - libxcb-keysyms1-dev
      - libxcb-randr0-dev
      - libxcb-shape0-dev
      - libxcb-util0-dev
      - libxcb-xinerama0-dev
      - libxcb-xkb-dev
      - libxcb-xrm0
      - libxcb-xrm-dev
      - libxcb1-dev
      - libxkbcommon-dev
      - libxkbcommon-x11-dev
      - xmlto

- name: Get latest download url
  shell:
    cmd: curl -sL https://api.github.com/repos/Airblader/i3/releases/latest | jq -r '.tag_name'
    warn: no
  register: p_version

- name: i3-gaps
  vars:
    version: "{{ p_version.stdout }}"
    asset: "i3-{{ version }}.tar.bz2"
    repo: "/tmp/i3-{{ version }}"
  block:

    - name: Download repo
      unarchive:
        src: "https://github.com/Airblader/i3/releases/download/{{ version }}/{{ asset }}"
        dest: /tmp
        remote_src: yes
        creates: "/tmp/{{ asset }}"

    - name: Generate build scripts
      command:
        cmd: autoreconf --force --install
        chdir: "{{ repo }}"
        creates: "{{ repo }}/configure"

    - name: Create build directory
      file:
        path: "{{ repo }}/build"
        state: directory

    - name: Generate Makefile
      command:
        chdir: "{{ repo }}/build"
        cmd: ../configure --prefix=/usr --sysconfdir=/etc --mandir=/usr/local/share/man --disable-sanitizers
        creates: "{{ repo }}/build/Makefile"

    - name: Compile
      make:
        chdir: "{{ repo }}/build"

    - name: Install
      become: yes
      make:
        chdir: "{{ repo }}"
        target: install

    - name: Remove repo
      file:
        path: "{{ repo }}"
        state: absent
