- name: Install dependencies
  become: true
  apt:
    state: latest
    name:
      - asciidoc
      - autoconf
      - automake
      - libev-dev
      - libpango1.0-dev
      - libstartup-notification0-dev
      - libyajl-dev
      - libxcb-cursor-dev
      - libxcb-icccm4-dev
      - libxcb-keysyms1-dev
      - libxcb-randr0-dev
      - libxcb-shape0-dev
      - libxcb-util0-dev
      - libxcb-xinerama0-dev
      - libxcb-xkb-dev
      - libxcb-xrm0
      - libxcb-xrm-dev
      - libxcb1-dev
      - libxkbcommon-dev
      - libxkbcommon-x11-dev
      - xmlto

- name: Get latest download url
  shell:
    cmd: curl -sL https://api.github.com/repos/Airblader/i3/releases/latest | jq -r '.assets[] | select(.name|endswith(".tar.xz")).browser_download_url'
    warn: no
  register: download_url
  changed_when: false

- name: Download and extract archive
  unarchive:
    remote_src: yes
    src: "{{ download_url.stdout }}"
    dest: /tmp/i3-gaps
    creates: /tmp/i3-gaps
    extra_opts:
      - --strip-components
      - 1

- name: Generate build scripts
  command:
    cmd: autoreconf --force --install
    chdir: /tmp/i3-gaps
    creates: /tmp/i3-gaps/configure

- name: Create build directory
  file: path=/tmp/i3-gaps/build state=directory

- name: Generate Makefiles
  command:
    chdir: /tmp/i3-gaps/build
    cmd: ../configure --prefix=/usr --sysconfdir=/etc --mandir=/usr/local/share/man --disable-sanitizers
    creates: /tmp/i3-gaps/build/Makefile

- name: Compile
  make: chdir=/tmp/i3-gaps/build

- name: Install
  become: true
  make: chdir=/tmp/i3-gaps/build target=install
  notify:
    - remove i3-gaps repo
