- name: Copy template
  become: true
  template: src=hosts.j2 dest=/etc/hosts

- name: Detect cloud-init
  stat: path=/etc/cloud/cloud.cfg get_checksum=false
  register: cloud_cfg

- name: Prevent cloud-init from modifying hostname
  become: true
  lineinfile:
    path: "{{ cloud_cfg.stat.path }}"
    regexp: "^preserve_hostname: false"
    line: "preserve_hostname: true"
  when: cloud_cfg.stat.exists
