- name: Install screenfetch
  apt: name=screenfetch state=latest

- name: Install custom header script
  become: yes
  copy:
    src: 00-custom-header
    dest: /etc/update-motd.d/00-custom-header
    mode: u=rwx,g=rx,o=rx
